# -*- coding: utf-8 -*-
"""Day3YapayZekaKampifirst95mindictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bkaiCfnKUBalUqw2eWMgFXwIpincu8tb
"""

araba = {
    "Marka" : "Ford",
    "Model" : "Mustang",
    "Electric" : False,
    "Yil" : 2020,
    "Renk" : ["Kirmizi", "Beyaz", "Mavi", "Sari"]
}
print(araba)
print(type(araba))
print(len(araba))
dictionary1 = araba["Yil"]
print(dictionary1)
dictionary2 = araba.get("Model")
print(dictionary2)
dictionary3 = araba["Renk"]
print(dictionary3)
dictionary4 = araba.get("Marka")
print(dictionary4)

if "Model" in araba:
  print("Arabanin modeli :" , araba.get("Model"))

dictionary5 = araba.keys()
print(dictionary5)
dictionary6 = araba.values()
print(dictionary6)
dictionary7 = araba.items()
print(dictionary7)

araba["Yil"] = "2018"
print(dictionary6)
araba.update({"Electric":"True"})
print(araba)
araba["Pesin Fiyat"] = 98000
araba.update({"120 Ay Vadeli Fiyat": 120000})
print(araba)

dictionary8 = {
    1:0,
    2:9,
    3:8,
    4:7,
    5:6
}
dictionary8.pop(5)
print(dictionary8)
dictionary8.popitem()
print(dictionary8)
dictionary8.popitem()
print(dictionary8)
dictionary8.popitem()
print(dictionary8)
del dictionary8[1]
print(dictionary8)
del dictionary8 #NameError: name 'dictionary8' is not defined
dictionary9 = {
    3:4,
    5:6
}
dictionary9.clear()
print(dictionary9)
dictionary10 = {
    "Student1" : "Kemal",
    "Student2" : "Kaan",
    "Student3" : "Kayhan"
}
for kisi in dictionary10:
  print(kisi)
  print(dictionary10[kisi])
for kisi in dictionary10.keys():
  print(kisi)
for kisi in dictionary10.values():
  print(kisi)
for kisi , adi in dictionary10.items():
  print(kisi , adi)

dictionary11 = dictionary10.copy()
print(dictionary11)
dictionary12 = dict(dictionary10)
print(dictionary12)

sinif1 = {
    "ogrenci1" : {
        "adi" : "Kemal",
        "yil" : 2009
    },
    "ogrenci2" : {
        "adi" : "Kaan",
        "yil" : 2012
    },
    "ogrenci3" : {
        "adi" : "Kayhan",
        "yil" : 2003
    }
}
print(sinif1)

ogrenci1 = {
    "adi" : "Kemal",
    "yil" : 2009
}
ogrenci2 = {
    "adi" : "Kaan",
    "yil" : 2012
}
ogrenci3 = {
    "adi" : "Kayhan",
    "yil" : 2003
}
sinif2 = {
    "ogrenci1" : ogrenci1,
    "ogrenci2" : ogrenci2,
    "ogrenci3" : ogrenci3
}
print(sinif2)