# -*- coding: utf-8 -*-
"""Day3YapayZekaKampituplefirst52min.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sIEawhUoRyFR7OY6_0I2TX2gpDXxhc5j
"""

cicekler = ("orkide", "papatya", "lale", "gul")
print(cicekler)
print(type(cicekler))
cicekler1 = tuple(("orkide", "papatya", "lale", "gul"))
print(cicekler1)
print(type(cicekler1))

tuple1 = ("elma" , "muz" , "kiraz")
tuple2 = (1 ,5 ,7 ,9 , 3)
tuple3 = (True, False, False)
tuple4 = ("abc", 34, True, 40, "merhaba")
print(tuple1)
print(tuple2)
print(tuple3)
print(tuple4)
print(len(tuple4))
print(tuple4[1:3])

if "merhaba" in tuple4:
  print ("Merhaba size de")
else:
  print("gunaydin")

list1 = list(tuple4)
list1[1] = "alakasiz"
tuple4 = tuple(list1)
print(tuple4)

ulkeler = ("Turkiye", "Almanya", "Kibris", "Italya", "ABD")
for ulke in ulkeler:
  print(ulke)
for ulke_sayisi in range(len(ulkeler)):
  print(ulkeler[ulke_sayisi])

ulke_sayisi = 0 
while ulke_sayisi < len(ulkeler):
  print(ulkeler[ulke_sayisi])
  ulke_sayisi = ulke_sayisi+1

tuple5 = tuple3 + tuple4
print(tuple5)

tuple6 = tuple3 * 2
print(tuple6)

kac_tane = tuple6.count(True)
print(kac_tane)
ilk_nerede1 = tuple6.index(True)
print(ilk_nerede1)
ilk_nerede2 = tuple6.index(False)
print(ilk_nerede2)