# -*- coding: utf-8 -*-
"""Day3YapayZekaKampifirst61minSets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bPm6cPGLulLgycqyRq_aTDnCRJ9NgXfX
"""

turler1 = {"roman", "oyku", "hikaye", "oyku"}
print(turler1)
print(type(turler1))
print(len(turler1))
turler2 = set(("roman", "oyku", "hikaye", "oyku"))
print(turler2)
print(type(turler2))
print(len(turler2))
set1 = {"elma", "armut", "kivi", "mango", "cilek"}
set2 = {1, 5, 7, 9, 3}
set3 = {True, False, False}
set4 = {"abc", 34, True, 40, "male"}
print("oyku" in turler1)
for book in turler1:
  print (book)
if "roman" in turler1:
  print( "Roman okuyor")
print(set4)
turler1.add("deneme")
print(turler1)
turler2ek = {"deneme", "aciklama"}
turler2.update(turler2ek)
print(turler2)
turler1.remove("oyku")
print(turler1)
turler2.discard("hikaye")
print(turler2)
set5 = {3, 4, 5}
print(set5)
set5.clear() #set()
print(set5)
del set5 #NameError: name 'set5' is not defined

set6 = set3.union(set4)
print(set6)

set7 = {"telefon", "bilgisayar", "tablet"}
set8 = {"tablet", "mobil", "pc"}
print(set7)
set9 = set7.intersection(set8)
print(set9)
set7.intersection_update(set8)
print(set7)

set10 = {"telefon", "bilgisayar", "tablet"}
set10.symmetric_difference_update(set8)
print(set10)

set11 = {"telefon", "bilgisayar", "tablet"}
set12 = set11.symmetric_difference(set8)
print(set12)