# -*- coding: utf-8 -*-
"""Ders2YapayZekaKampifirst100min.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g-Q1DKRfb_s6Z8XMOhYWVAnRVe7tgJaJ
"""

degisken1 = str ("Elif Hoca")
degisken2 = int ("25")
degisken3 = float ("1.25")
print(degisken1)
print(degisken2)
print(degisken3)

x, y, z = "Elma", "Armut", "Portakal"
print(x)
print(y)
print(z)

x, y, z = "Elma", "Elma","Elma"
print(x)
print(y)
print(z)

meyveler = "Elma", "Armut", "Portakal"
x, y, z = meyveler
print(x)
print(y)
print(z)

import random
rastgeleSayi = random.randrange(1 ,10)
print(rastgeleSayi)

kullaniciAdi = input("Kullanici adiniz nedir? ")
print("Sizin kulanici adiniz: ", kullaniciAdi)

toplam1 = input("ilk sayiyi verin: ")
toplam2 = input("ikinci sayiyi verin: ")
print(toplam1 + toplam2)
print(type(toplam1))
toplam3 = int(input("Ucuncu sayiyi verin : "))
toplam4 = int(input("Dorduncu sayiyi verin : "))
print(toplam3 + toplam4)
print(type(toplam3))
toplam5 = float(input("Besinci sayiyi verin : "))
toplam6 = float(input("Altnci sayiyi verin : "))
print(toplam5+toplam6)
print(type(toplam5))

sayi11 = 6
sayi12 = 8
print(sayi11>=sayi12)
print(sayi11<=sayi12)

sayi13 = 200
sayi14 = 500
if (sayi13>sayi14):
  print(str(sayi13) + ", " + str(sayi14) +" ten buyuktur.")
elif (sayi13<sayi14):
  print(str(sayi13) + ", " + str(sayi14) +" ten kucuktur.")
else:
  print("iki sayi birbirine esittir.")

sayi15 = int(input("ilk sayiyi verin : "))
sayi16 = int(input("ikinci sayiyi verin : "))
if (sayi15>sayi16):
  print(str(sayi15) + ", " + str(sayi16) +" ten buyuktur.")
elif (sayi15<sayi16):
  print(str(sayi15) + ", " + str(sayi16) +" ten kucuktur.")
else:
  print("iki sayi birbirine esittir.")

sayi15 = float(input("ilk sayiyi verin : "))
sayi16 = float(input("ikinci sayiyi verin : "))
if (sayi15>sayi16):
  print(str(sayi15) + ", " + str(sayi16) +" ten buyuktur.")
elif (sayi15<sayi16):
  print(str(sayi15) + ", " + str(sayi16) +" ten kucuktur.")
else:
  print("iki sayi birbirine esittir.")

sayi17 = 4
sayi17 = sayi17 + 3
print(sayi17)
sayi17 += 3
print(sayi17)

sayi18 = 7
sayi18 = sayi18 - 4
print(sayi18)
sayi18 -=4
print(sayi18)

sayi19 = 0
while sayi19 < 7:
  print(sayi19)
  sayi19 += 1
else:
  print("bitti")

sayi20 = 0
while sayi20 < 7:
  print(sayi20)
  sayi20 += 1
  if sayi20 == 3:
    print("3 sayisi bulundu")
    break
else:
  print("bitti")

sayi21 = 0
while sayi21 < 7:
  print(sayi21)
  sayi21 += 1
  if sayi21 == 3:
    print("3 sayisi bulundu")
    continue
else:
  print("bitti")