# -*- coding: utf-8 -*-
"""Ders2YapayZekaKampiFirst114MinTakeThreeNumbersGiveInOrder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o60E04LiFgWjK6qBsH_ITAXyv3cO0ten
"""

sayi1 = 56
print(sayi1<4 and sayi1>98)
print(sayi1>4 and sayi1<98)
print(sayi1==4 or sayi1<98)
print(sayi1==4 or sayi1>98)

sayi2 = int(input("Sayiyi verin : "))
print(sayi2>4 and sayi2<98)

sayi3 = int(input("ilk sayiyi verin : "))
sayi4 = int(input("ikinci sayiyi verin : "))
sayi5 = int(input("ucuncu sayiyi verin : "))
if(sayi3<sayi4):
  print(str(sayi4) + " " + "is bigger than "+ str(sayi3))
  if(sayi4<sayi5):
    print(str(sayi5) + " is the biggest")
    print(str(sayi3)+ "<" + str(sayi4) + "<" +str(sayi5))
    print("kucukten buyuge {" +str(sayi3) + ", " + str(sayi4) + ", " + str(sayi5)+"}")
  elif(sayi4>sayi5):
    print(str(sayi4) + " is the biggest")
    if(sayi3<sayi5):
      print(str(sayi3)+ "<" + str(sayi5) + "<" +str(sayi4))
      print("kucukten buyuge {" + str(sayi3) + ", " + str(sayi5) + ", " + str(sayi4) + "}")
    elif(sayi3>sayi5):
      print(str(sayi5)+ "<" + str(sayi3) + "<" +str(sayi4))
      print("kucukten buyuge {" + str(sayi5) + ", " + str(sayi3) + ", " + str(sayi4) + "}")
    else:
      print(str(sayi3)+ "=" + str(sayi5) + "<" +str(sayi4))
      print("kucukten buyuge :ilk sayi esittir ucuncu sayiya ve ikisi kucuktur ikinci sayidan")
  else:
    print(str(sayi5) + " is the biggest")
    print(str(sayi3)+ "<" + str(sayi4) + "=" +str(sayi5))
    print("kucukten buyuge : ilk sayi kucuktur birbirine esit olan ikinci ve ucuncu sayidan")

elif(sayi3>sayi4):
  print(str(sayi4) + " " + "is less than "+ str(sayi3))
  if(sayi3<sayi5):
    print(str(sayi5) +" is the biggest")
    print(str(sayi4)+ "<" + str(sayi3) + "<" +str(sayi5))
    print("kucukten buyuge {" + str(sayi4) + ", " + str(sayi3) + ", " + str(sayi5) + "}")
  elif(sayi3>sayi5):
    print(str(sayi3) +" is the biggest")
    if(sayi4<sayi5):
      print(str(sayi4)+ "<" + str(sayi5) + "<" +str(sayi3))
      print("kucukten buyuge {" + str(sayi4) + ", " + str(sayi5) + ", " + str(sayi3) + "}")
    elif(sayi4>sayi5):
      print(str(sayi5)+ "<" + str(sayi4) + "<" +str(sayi3))
      print("kucukten buyuge {" + str(sayi5) + ", " + str(sayi4) + ", " + str(sayi3) + "}")
    else:
      print(str(sayi5)+ "=" + str(sayi4) + "<" +str(sayi3))
      print("kucukten buyuge :ikinci sayi esittir ucuncu sayiya ve ikisi kucuktur ilk sayidan")
  else:
    print(str(sayi5) + " is the biggest")
    print(str(sayi4)+ "<" + str(sayi3) + "=" +str(sayi5))
    print("kucukten buyuge : ikinci sayi kucuktur birbirine esit olan ilk ve ucuncu sayidan")
    
else:
  if(sayi3>sayi5):
    print(str(sayi3) + " is the biggest")
    print(str(sayi5)+ "<" + str(sayi4) + "=" +str(sayi3))
    print("kucukten buyuge : ucuncu sayi kucuktur birbirine esit olan ilk ve ikinci sayidan")
  elif(sayi3<sayi5):
    print(str(sayi5) + " is the biggest")
    print(str(sayi3)+ "=" + str(sayi4) + "<" +str(sayi5))
    print("kucukten buyuge :ilk sayi esittir ikinci sayiya ve ikisi kucuktur ucuncu sayidan")
  else:
    print("butun sayilar esit")