# -*- coding: utf-8 -*-
"""Ders2YapayZekaKampifirst46min.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ltMqd-C9PzmkGqzfRBvFkFXDOObOUCz
"""

print("merhaba dunya")

sayi = 5
if sayi< 0:
  print("Sayi negatif")
else:
  print("Sayi negatif degil")

i =1 
carp=1
while i !=0:
  carp *=i
  print(carp)
  i =int(input("Sayi gir"))

for x in range(4 ,55 ,10):
  print(x)

for x in range(4, 5500, 1000):
  print(x)

metin = "Merhaba, x iyi misin?"
for x in metin:
  if x == "x":
    continue
  print(x)

metin = "Merhaba, x iyi misin?"
for x in metin:
  if x == "x":
    break
  print(x)

x = 200
print(isinstance(x, int))

tamsayi = 100
ondalikliSayi = 1.5
metin2 = "Herkese Merhaba"
print(tamsayi)
print(type(tamsayi))
print(ondalikliSayi)
print(type(ondalikliSayi))
print(metin2)
print(type(metin2))

tamsayi = "100"
ondalikliSayi = "1.5"
metin2 = "Herkese Merhaba"
print(tamsayi)
print(type(tamsayi))
print(ondalikliSayi)
print(type(ondalikliSayi))
print(metin2)
print(type(metin2))

tamsayi = int("100")
print(tamsayi)
print(type(tamsayi))

tamsayi = "100"
print(int(tamsayi))
print(type(tamsayi))

ondalikliSayi =float("1.5")
print(ondalikliSayi)
print(type(ondalikliSayi))