# -*- coding: utf-8 -*-
"""Ders2YapayZekaKampifirst150min.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12cIdHJDDCG0RdAiPbx7SDQI72DFXdJoc
"""

sayi1=int(input("Sayi1 giriniz: "))
sayi2=int(input("Sayi2 giriniz: "))
sayi3=int(input("Sayi3 giriniz: "))
if(sayi1<sayi2 and sayi3<sayi1):
  print("En kücük sayi : ", sayi3)
  print("Ortadaki sayi : ", sayi1)
  print("En büyük sayi : ", sayi2)
  #3<1<2
elif(sayi1<sayi2 and sayi3==sayi1):
  print("En kücük sayi (2 kere): ", sayi3)
  print("En büyük sayi : ", sayi2)
  #3=1<2
elif(sayi1<sayi2 and sayi1<sayi3):
  print("En kücük sayi : " ,sayi1)
  if(sayi2==sayi3):
    print("En buyuk sayi (2 kere): " , sayi2)
    #1<2=3
  elif(sayi2<sayi3):    
    print("Ortadaki sayi : ", sayi2)
    print("En buyuk sayi : ", sayi3)
    #1<2<3
  elif(sayi3<sayi2):
    print("Ortadaki sayi : ", sayi3)
    print("En buyuk sayi : ", sayi2)
    #1<3<2
elif(sayi2<sayi1 and sayi3==sayi1):
  print("En kücük sayi : ", sayi2)
  print("En büyük sayi (2 kere): ", sayi1)
  #3=1<2
elif(sayi2<sayi1 and sayi1<sayi3):
  print("En kücük sayi : ", sayi2)
  print("Ortadaki sayi : ", sayi1)
  print("En büyük sayi : ", sayi3)
  #2<1<3
elif(sayi2<sayi1 and sayi3<sayi1):
  print("En buyuk sayi : ", sayi1)
  if(sayi2==sayi3):
    print("En kucuk sayi (2 kere): " , sayi2)
    #2=3<1
  elif(sayi2<sayi3):
    print("En kucuk sayi : ", sayi2)
    print("Ortadaki sayi : ", sayi3)
    #2<3<1
  elif(sayi3<sayi2):
    print("En kucuk sayi : ", sayi3)
    print("Ortadaki sayi : ", sayi2)
    #3<2<1

elif(sayi1==sayi2 and sayi3<sayi1):
  print("En kücük sayi : ", sayi3)
  print("En büyük sayi (2 kere): ", sayi2)
  #3<1=2
elif(sayi1==sayi2 and sayi1<sayi3):
  print("En kücük sayi (2 kere): ", sayi1)
  print("En büyük sayi : ", sayi3)
  #3<1=2
elif(sayi1==sayi2 and sayi3==sayi1):
  print("Sayilar birbirine esittir :",sayi3)
  metin = "Sayilar birbirine esittir : {}"
  print(metin.format(sayi3))
  #3=1=2

x = ["elma", "muz", "armut"]
y = ["elma", "muz", "armut"]
z = x
print(x is z)
print(x is y)
print(x == y)
if(x is not y):
  print("Ayni nesne degil.")
if(z is x):
  print("Ayni nesneler.")
print("elma" in x)
if("elma" in y):
  print("Dizinde elma bulundu.")

for x in "robotik":
  print(x)

metin1 = """Are 
you 
ready?"""
print(metin1)

metin2 = "Okul"
print(metin2[3])
print(metin2[0:2])
print(len(metin2))
print(metin2[-4:-1])

metin3 = "Python dersinde hos bulduk."
print("hos" in metin3)
print("hoş" not in metin3)

metin4 = input("Aranacak ismi verin : ")
metin5=("kamil, mert, hayri, akin")
metin6 = metin4.lower()
if(metin6 in metin5):
  print("Isim bulundu.")

yas1 = 34
metin7 = "Merhaba, yasim {}"
print(metin7.format(yas1))
adi1 = "Erdem"
boyu1 = 1.56
metin8 = "Merhaba, benim adim {}, yasim {} ve boyum {}"
print(metin8.format(adi1, yas1, boyu1))
yas2 = int (input("Yasinizi verin : "))
adi2 = input("Adinizi verin :")
boyu2 = float (input("Boyunuzu verin : "))
metin8 = "Merhaba, benim adim {}, yasim {} ve boyum {}"
print(metin8.format(adi2, yas2, boyu2))